# Generated by Django 3.0.5 on 2021-04-13 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('confianza', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('blacklist', models.CharField(choices=[('C', 'Confiable'), ('I', 'Intermedio'), ('N', 'No confiable')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Verbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.TextField()),
                ('radicalRegular', models.TextField(blank=True, null=True)),
                ('radicalIrregular_0', models.TextField(blank=True, null=True)),
                ('radicalIrregular_1', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
