# Generated by Django 3.0.6 on 2020-05-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='blacklist',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
