# Generated by Django 3.0.6 on 2020-07-05 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0002_dominio_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominio',
            name='ranking',
        ),
        migrations.AddField(
            model_name='dominio',
            name='confianza',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
