# Generated by Django 3.0.6 on 2020-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0003_auto_20200705_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='blacklist',
            field=models.BooleanField(choices=[('C', 'Confiable'), ('I', 'Intermedio'), ('B', 'Blacklisted')]),
        ),
    ]
