# Generated by Django 3.0.6 on 2020-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0005_auto_20200908_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='blacklist',
            field=models.CharField(choices=[('C', 'Confiable'), ('I', 'Intermedio'), ('N', 'No confiable')], max_length=128),
        ),
    ]
