# Generated by Django 3.0.6 on 2020-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0006_auto_20200908_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.TextField()),
                ('radicalRegular', models.TextField()),
                ('radicalIrrecular_0', models.TextField()),
                ('radicalIrrecular_1', models.TextField()),
            ],
        ),
    ]
