# Generated by Django 3.0.6 on 2020-10-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0007_verbos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verbos',
            new_name='Verbo',
        ),
    ]
