# Generated by Django 3.0.6 on 2020-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0009_auto_20201015_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbo',
            name='radicalIrrecular_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbo',
            name='radicalIrrecular_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verbo',
            name='radicalRegular',
            field=models.TextField(blank=True, null=True),
        ),
    ]
